# Generated by Django 4.0.3 on 2022-05-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
