# Generated by Django 4.0.3 on 2022-05-11 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_booking_available_alter_payment_admin_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='del_booking',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
